### ISSUE TITLE
Tag a (stable) release?

### ISSUE THREAD

**Issue by bfontaine** [DanielVartanov/willgit#1]
Hello,

I know this repo hasn’t been updated for ~1 year but it’d be very helpful if you could tag a release so we know the code there is stable and can be used. I work on [Homebrew](http://brew.sh/) and we provide a way to install `willgit` but we rely on the git HEAD so can’t provide checksums and can’t ensure users will always get the same code depending on the time they install it, making it harder for us to debug issues.

Thanks!

**Comment by DanielVartanov** [comment]
Hi @bfontaine, sure, huge thanks for maintaining a brew package of willgit.
How exactly do you want me to tag it? A git tag `stable`? Or make a release? How?
Thanks

**Comment by bfontaine** [comment]
@DanielVartanov A git tag like `0.1.0` or the version you want would be great!

**Comment by DanielVartanov** [comment]
Done. Thanks again for your effort!

**Comment by bfontaine** [comment]
Thank _you_! :tada:
